### ISSUE TITLE
Adding header to XHR calls

### ISSUE THREAD

**Issue by jussimattila** [cornerstonejs/cornerstone-nifti-image-loader#11]
Impressive work on the Nifti loader! I've implemented a hacky Nifti loader for use with our tools and I'm considering to update to using this library instead of the in-house solution.

How would you add support for modifying the headers (I need to submit a JWT bearer token) of the outgoing XHR requests? I'm open to creating a PR if you have some pointers where to start.

**Comment by dannyrb** [comment]
I'm not super familiar with this repository, but this may be a good place to start your search:

https://github.com/flywheel-io/cornerstone-nifti-image-loader/blob/087154de68e38d8c66cc707ef897122627e85bb5/src/nifti/VolumeAcquisition.js#L31

FWIW, the `cornerstone-wado-image-loader` allows you to configure the XHR's `beforeSend` to add headers. If this library doesn't already support the functionality, configurable customer headers sounds like a good value add.

**Comment by jussimattila** [comment]
Yeah, I've used `beforeSend` with `cornerstone-wado-image-loader` to inject the bearer token. But, I don't see a way to provide `httpHeaders` from outside in the current code base, so I suppose a PR is needed.

If there is anyone more familiar with the library who can comment, please do so!

As a side note, the npm package for this library is from late last year, but there have been a few updates to the repo during this year. Is this intentional?

**Comment by jussimattila** [comment]
Sorry, I forgot to mention that I actually found the way to do this with the nifti loader:
```
cornerstoneNiftiImageLoader.nifti.configure({
        headers: {
            Authorization: "Bearer " + e.token.encoded
        }
    });
```

**Comment by Lichking1** [comment]
> Sorry, I forgot to mention that I actually found the way to do this with the nifti loader:
> 
> ```
> cornerstoneNiftiImageLoader.nifti.configure({
>   headers: {
>     Authorization: "Bearer " + e.token.encoded
>   }
> });
> ```

Hi, I have faced the similar issue, for the wado image loader, I used 
`beforeSend(xhr) {
                xhr.setRequestHeader('Authorization', jwt);
              }`
but how am I going to change to e.token.encoded? the direct concatenation for bearer + jwt seems not working
